site_name:        EEG.jl
repo_url:         https://github.com/codles/EEG.jl
site_description: Process EEG files with Julia
site_author:      Robert Luke

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Examples:
    - ASSR: examples/ASSR.md
    - Source Analysis: examples/source.md
